<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>my</string>
	</array>
	<key>name</key>
	<string>Myco</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Constant</string>
			<key>match</key>
			<string>\b[A-Z]\w*\b</string>
			<key>name</key>
			<string>support.class.myco</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.myco</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.myco</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>id Binding</string>
			<key>match</key>
			<string>(id)\s*:\s*(.+)</string>
			<key>name</key>
			<string>meta.idbinding.myco</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.decorator.myco</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.decorator.myco</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.myco</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Binding</string>
			<key>match</key>
			<string>((\w+\s+)*)(\w+)(?=\s*:)</string>
			<key>name</key>
			<string>meta.binding.myco</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.ruby</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.myco</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.ruby</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Category</string>
			<key>match</key>
			<string>(\[)([^]]*)(\])</string>
			<key>name</key>
			<string>meta.category.myco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Function Call (with braces)</string>
			<key>match</key>
			<string>(\w+)(?=\s*\()</string>
			<key>name</key>
			<string>entity.name.function</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\|)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.parameter.ruby</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Parameters</string>
			<key>end</key>
			<string>(\|)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>([=:])</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.assignment.ruby</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>The default value of a parameter following an =</string>
					<key>end</key>
					<string>(?=[,|])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.ruby</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>comment</key>
					<string>The name of a parameter</string>
					<key>match</key>
					<string>[_a-zA-Z][_a-zA-Z0-9]*</string>
					<key>name</key>
					<string>variable.parameter.myco</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>The comma separator for parameters</string>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>punctuation.separator.parameter.myco</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.ruby</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>source.ruby</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.myco</string>
	<key>uuid</key>
	<string>2382235e-084e-4181-8783-337e31e15474</string>
</dict>
</plist>
